import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { requests, transactions, validateTransaction, createDispute, money, type Dispute } from './domain';
import './styles.css';

function App() {
  const [screen, setScreen] = useState<'inbox' | 'transactions'>('inbox');
  const [selectedId, setSelectedId] = useState(requests[0].id);
  const [query, setQuery] = useState('');
  const [searchedId, setSearchedId] = useState<string | null>(null);
  const [verified, setVerified] = useState(false);
  const [disputes, setDisputes] = useState<Dispute[]>([]);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const request = requests.find(item => item.id === selectedId)!;
  const transaction = transactions.find(item => item.id === searchedId);
  const validation = validateTransaction(request, transaction);
  const completed = disputes.find(item => item.requestId === request.id);
  function clearSearch() { setQuery(''); setSearchedId(null); setVerified(false); setError(''); }
  function navigate(next: 'inbox' | 'transactions') { setScreen(next); setError(''); }
  function reset() { setDisputes([]); setSelectedId(requests[0].id); clearSearch(); setScreen('inbox'); setNotice('Demo data reset. All three requests are ready to review.'); }
  function submitCase() {
    try { const dispute = createDispute(request, transaction, verified, disputes); setDisputes(items => [...items, dispute]); setError(''); }
    catch (err) { setError(err instanceof Error ? err.message : 'Unable to create dispute.'); }
  }
  return <div className="app">
    <aside className="sidebar">
      <a className="brand" href="#main" aria-label="ShadowBank Lite main content"><span className="brand-mark">S</span><span>ShadowBank<span className="brand-sub">LITE / OPERATIONS</span></span></a>
      <div className="nav-label">WORKSPACE</div>
      <nav aria-label="Main navigation"><button className={screen === 'inbox' ? 'nav active' : 'nav'} aria-current={screen === 'inbox' ? 'page' : undefined} onClick={() => navigate('inbox')}><span>Inbox</span><span className="count">{requests.length - disputes.length}</span></button><button className={screen === 'transactions' ? 'nav active' : 'nav'} aria-current={screen === 'transactions' ? 'page' : undefined} onClick={() => navigate('transactions')}>Transactions</button></nav>
      <div className="sidebar-bottom"><span className="demo-dot"/> Local demo environment<p>Synthetic records only.<br/>ShadowOps AI hackathon</p></div>
    </aside>
    <div className="workspace"><header className="topbar"><span>Payment operations <span className="slash">/</span> Disputes</span><button className="secondary reset" onClick={reset}>Reset Demo Data</button></header>
    <main id="main"><div className="page-heading"><div><h1>{screen === 'inbox' ? 'Customer inbox' : 'Transaction review'}</h1><p>{screen === 'inbox' ? 'Review customer requests and start a payment investigation.' : 'Find the payment, verify the details, and create a dispute.'}</p></div><span className="local-label">LOCAL SANDBOX</span></div>
      <div role="status" className={notice ? 'notice' : ''}>{notice}</div>
      <ol className="steps" aria-label="Dispute workflow"><li className={screen === 'inbox' ? 'current' : ''}><span>1</span> Review request</li><li className={screen === 'transactions' && !completed ? 'current' : ''}><span>2</span> Verify transaction</li><li className={completed ? 'current' : ''}><span>3</span> Create dispute</li></ol>
      {screen === 'inbox' ? <div className="inbox-layout"><section className="request-list" aria-label="Customer requests"><div className="section-header"><h2>Requests</h2><span>{requests.length} seeded</span></div>{requests.map(item => <button key={item.id} className={`request-item ${item.id === selectedId ? 'selected' : ''}`} aria-pressed={item.id === selectedId} onClick={() => { setSelectedId(item.id); clearSearch(); setNotice(''); }}><span className="request-top"><strong>{item.name}</strong><span className={`badge ${disputes.some(d => d.requestId === item.id) ? 'resolved' : ''}`}>{disputes.some(d => d.requestId === item.id) ? 'Case created' : 'Needs review'}</span></span><span className="subject">{item.subject}</span><span className="request-bottom"><span>{item.customerId}</span><strong>{money(item.amountCents)}</strong></span></button>)}</section>
      <section className="panel detail"><div className="section-header"><h2>Request details</h2><span className="mono">{request.id}</span></div><div className="detail-body"><div className="customer"><span className="avatar">{request.name.split(' ').map(s => s[0]).join('')}</span><div><h3>{request.name}</h3><span className="muted">Customer {request.customerId}</span></div></div><h2 className="subject-heading">{request.subject}</h2><p className="message">{request.message}</p><dl className="facts"><div><dt>Transaction ID</dt><dd className="mono">{request.transactionId}</dd></div><div><dt>Disputed amount</dt><dd>{money(request.amountCents)}</dd></div><div><dt>Customer ID</dt><dd className="mono">{request.customerId}</dd></div><div><dt>Currency</dt><dd>{request.currency}</dd></div></dl><div className="hint">Use the customer's transaction reference to find the payment. Check all details before opening a case.</div><button className="primary" onClick={() => { clearSearch(); navigate('transactions'); }}>{completed ? 'View created dispute' : 'Investigate transaction'} <span aria-hidden="true">→</span></button></div></section></div>
      : <div className="review-layout"><aside className="panel context"><div className="section-header"><h2>Selected request</h2></div><div className="detail-body"><h3>{request.name}</h3><p className="muted">{request.subject}</p><dl className="facts single"><div><dt>Customer ID</dt><dd className="mono">{request.customerId}</dd></div><div><dt>Transaction ID to find</dt><dd className="mono">{request.transactionId}</dd></div><div><dt>Disputed amount</dt><dd>{money(request.amountCents)} {request.currency}</dd></div></dl><button className="text-button" onClick={() => navigate('inbox')}>← Return to inbox</button></div></aside>
      <section className="panel"><div className="section-header"><h2>{completed ? 'Dispute confirmation' : 'Find a transaction'}</h2></div><div className="detail-body">{completed ? <div className="success" role="status"><div className="success-icon" aria-hidden="true">✓</div><h2>Dispute case created</h2><p>The request is linked to the verified payment.</p><dl className="facts"><div><dt>Case ID</dt><dd className="mono">{completed.id}</dd></div><div><dt>Transaction ID</dt><dd className="mono">{completed.transactionId}</dd></div><div><dt>Customer ID</dt><dd className="mono">{completed.customerId}</dd></div><div><dt>Amount</dt><dd>{money(completed.amountCents)} {completed.currency}</dd></div></dl><div className="validation">Validation passed · Correct transaction used</div><button className="primary" onClick={() => navigate('inbox')}>Back to inbox</button></div> : <><form onSubmit={event => { event.preventDefault(); setSearchedId(query.trim().toUpperCase()); setVerified(false); setError(''); }}><label htmlFor="transaction-id">Transaction ID</label><div className="search-row"><input id="transaction-id" required value={query} placeholder="Enter transaction ID" autoComplete="off" spellCheck={false} onChange={event => { setQuery(event.target.value); setSearchedId(null); setVerified(false); setError(''); }}/><button className="primary" type="submit">Search transaction</button></div><p className="input-help">Search the exact reference from the customer request.</p></form>
      {searchedId !== null && <div aria-live="polite">{transaction ? <><div className="result-heading"><h3>Transaction found</h3><span className="badge resolved">{transaction.status}</span></div><dl className="facts"><div><dt>Transaction ID</dt><dd className="mono">{transaction.id}</dd></div><div><dt>Customer ID</dt><dd className="mono">{transaction.customerId}</dd></div><div><dt>Merchant</dt><dd>{transaction.merchant}</dd></div><div><dt>Amount</dt><dd>{money(transaction.amountCents)} {transaction.currency}</dd></div><div><dt>Payment date</dt><dd>{transaction.date}</dd></div></dl><div className={validation.valid ? 'validation' : 'error'}>{validation.message}</div><label className="checkbox"><input type="checkbox" checked={verified} disabled={!validation.valid} onChange={event => setVerified(event.target.checked)}/><span>I have verified the transaction ID, customer ID, amount and currency against the customer request.</span></label><button className="primary" disabled={!validation.valid || !verified} onClick={submitCase}>Create dispute case</button></> : <div className="empty-result"><h3>No transaction found</h3><p>No local record matches <strong className="mono">{searchedId}</strong>. Check the reference with the customer. A dispute cannot be created without a matching transaction.</p></div>}</div>}{error && <p className="error" role="alert">{error}</p>}</>}</div></section></div>}
      <footer>ShadowBank Lite <span>Fictional banking sandbox · Data stays in this tab · Reset or reload to start again</span></footer>
    </main></div>
  </div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
